### ISSUE TITLE
Project proposal - limitations

### ISSUE THREAD

**Issue by dakaizou** [umbcs410-utimaco/crypto-analysis#10]
Please add foreseeable limitations.

**Comment by drewjax** [comment]
- Data from the Bitcoin blockchain is limited to: Time of transaction, total input and output of BTC sent/received, each parties address, value at time of transaction, along with a few other less relevant data points. 

- There is no open-source or public method to determine whether a wallet has been deemed "suspicious" and without using any of the users real life personal data, the information on the blockchain is all that is observable in achieving our goal.  

- Data and analytics presented to the user/customer is capped at the Bitcoin address and its transactions, and the connection to the suspected criminal is up to the user to be confirmed.
