### ISSUE TITLE
Project proposal - definitions

### ISSUE THREAD

**Issue by dakaizou** [umbcs410-utimaco/crypto-analysis#11]
Please define any acronyms that you use later in the proposal. (e.g., HTML: Hypertext Markup Language)

**Comment by drewjax** [comment]
-BTC: Bitcoin the cryptocurrency of choice that we will be using to track suspicious transactions of. Bitcoin uses blockchain technology which is a virtual currency that is public to all that uses it.

-Blockchain: technology works as a large public link of blocks of transaction. Bitcoin records a new block around every 10 minutes on average including unique hashes that tree to each individual transaction. Every block rewards its miner 6.25 BTC which halves every 4 years. Observable information at https://www.blockchain.com/explorer?view=btc.

-BTC address: it the unique string of letters and numbers that a user is given when creating a wallet where they store their Bitcoin and use for transaction destinations. 

-Sigma.js: Useful JavaScript library for graph making
-HTML: Hypertext Markup Language
-CSS: Cascade Style Sheets
-UI: User Interface
-JS: JavaScript
-HTTP: Hypertext Transfer Protocol
