### ISSUE TITLE
Project proposal - workflows

### ISSUE THREAD

**Issue by dakaizou** [umbcs410-utimaco/crypto-analysis#18]
Please identify and list the main workflows of the software product. Meaning, what does the actor do to achieve a certain goal.

Please model the workflows as UML Activity Diagrams.

**Comment by drewjax** [comment]
Our process will work as our user is presented with the user prompt to input a certain BTC address that has been deemed suspicious. Using the blockchain API, we will access all retrievable data and present in a visual and analytical manner. Once the data has been retrieved, it will pass through our application and back to the user to get a overview of its transactions for them to be able to make the real life connection behind the BTC wallet and take action if needed.
[Workflow Utimaco.pdf](https://github.com/umbcs410-utimaco/crypto-analysis/files/8158331/Workflow.Utimaco.pdf)

**Comment by muhanedg** [comment]
To start the user will see a graph with random wallets displayed and scroll through. When necessary, the user will be able to search a specific wallet and in the next page, they will generate a graph with wallets represented as circles with their address written in the middle. the wallets will have lines connecting to them to show the transaction. When clicking on the wallet a time stamp of the transaction will be shown and other transactions within that wallet. When the user wants they can easily search another wallet at any point by searching the address.
